language: node_js

branches:
  only:
    - master

before_script:
  - npm install

script:
  - gulp release

after_success:
  - bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/koluku/stella.git
  - secure: "N8WzH39gVwY5csKTapFeSFbWsVHhrg3+NEuryldUq1TMN4NWVvnmy/PNCxT9Te6dNo8SnD9mlAMlR61NqaCYNAduXqeHPNCCOXY++ENtVCkc7I1bisvO6mEB5RcwCOieCMm9DF3BUxbBS6JCY493ffpS8dOfbz2PGbEZzFYzUSdVkEKh9HsTDrkCrMjs/35EExNQw7oU65ig9t041fM8jjwKhhvwDDtTHw3VYe7RoOBbx6rz9VBtWWAqmb0oeUt7NDm+o4WeOisPCWK0ZGVixCVJDNXHYlhX+P3GhVwf5x0keaLJXoZWSFlq6RAYR6EJpSDirNRbi9JoYd3xy259WuyaMK3OYqz2bm4LDCypsb4C8TaTY6IPChD7qI7bPn78KYiAFWuEDDuXEWRERxx1nYiIOEatFUN56bMyxMBxrfHDvXg/3P69HWKryVshZ6PbZoaYKFvzIf42t81YT/e7AEsLu2qYSPpvZN3sT1YHqkYPKDfAFwfIJ5XZ/Ao5DWVNY11rzPQDrxdaIJFgPvErxp+gvG7FJxLnkCjuwaTEV5F1zJ+aBsbRnGxZnUtqgxZpdKdF9FUKZbXQBSkCMNCsvycNIGMHv7yH++GM87bAN/cIZsaf3kSrIHOImKew+re/QpzhFhk6h/fj+mgpL8SZYmkAkvMCDgtEQLkU69nSVO8="
